os:
- linux
- mac

language:
- node_js

node_js:
- '6.5'

branches:
  only:
  - /^ready\/.*$/

sudo: required

install:
  - echo Install Dependencies
  - npm install
  - sudo apt-get install python-pip python-dev
  - sudo pip install dronekit
  - sudo pip install dronekit-sitl

before_script:
  - echo Start Virtual Screen
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - echo Package project
  - npm run package:linux
  - npm run package:mac

jobs:
  include:
    - stage: Test
      script:
      - npm run test

    - stage: Integration
      script:
      - |-
        git clone "https://github.com/"$TRAVIS_REPO_SLUG".git" temp_repo;
        cd temp_repo;

        echo Mergin;
        git merge --ff-only origin/"$TRAVIS_BRANCH";

        echo Pushing;
        git push https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG master;

    - stage: Code Coverage

      script:
        - npm run coverage
        - npm run check


    - stage: Deliver GitHub Release

      before_deploy:
      - |-
        git checkout master
        echo "Deploying to GitHub releases ..."
        echo Pull Tags;
        git fetch --tags;

        echo get Latest Tag;
        VERSION=`git describe --tags $(git rev-list --tags --max-count=1)`;
        VERSION_BITS=(${VERSION//./ });
        VNUM1=${VERSION_BITS[0]};
        VNUM2=${VERSION_BITS[1]};
        VNUM3=${VERSION_BITS[2]};
        echo $VERSION;

        echo Tag update;

        VNUM3=$((VNUM3+1));

        NEW_TAG="$VNUM1.$VNUM2.$VNUM3";
        echo "Updating $VERSION to $NEW_TAG";
        git tag $NEW_TAG;
        git push -q https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG --tags;

      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file:
        - zip "out/rct-groundcontrol-darwin-x64/rct-groundcontrol.app/Contents/MacOS/rct-groundcontrol"
        - "out/rct-groundcontrol-linux-x64/rct-groundcontrol"
        skip_cleanup: true
        on:
          tags: false
          all_branches: true

    - stage: Delete old branch
      script: git push https://$GH_TOKEN@github.com/"$TRAVIS_REPO_SLUG" --delete "$TRAVIS_BRANCH";


cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
    on_failure: change
env:
  global:
    secure: rtXOe/h1xXzFgq6MhWVpkNfVwO9TafMZBzq0NExniEcxAQPgxI+R2OkBNd9nndljtTExVKrD2EaVy1PtlV8X984tSVpRKAROXUhAaajnlVmG6jJ2hW9rbqb2Bs4PB4mUeift9B+LACSdAfkBewNGKWcqShXl6qaxNXxkrV8IwwixhS19dA+P4M/Nd62huUw/TCP6px6KTiRk8mPsHrUs2PtPXH8CZJ72tuI233qZgb7JzKmFvcl/6s4+8Z6Jv6/xW5zg0LWo3Nj/UrapcqQfu/+isGumr3GQ82C1CYCceVvjtIbP797tlKWlwOvefoK3bLhF7uvQbTFmbziqJeAl5OgfGqnkNj5YOcEj+7XGZ39XbpdvTGuIbwNP0Hb3Yh8HH6NR7ZEHT05mIg26maiRdwTEXDHkyfADzwgqy40Gyh+mtAH8DJZ2HJXd5mQof4lbljPkzIwkdFZEF3n77ZKOIFPqxTMtQHQurK4ONmZEIJxxlr/xmeG/QWSfsrk2KtegnXCgVURltY6cFST2ZgTURdT6wjX4Rgtt2uTqtHi50YzjR4RT5xlmXy69iFSts/OVcdjZaYQXknr9tUfeNUefyGTpWiujjjynLLBElTYZKAdnmVzw2xBf5yghSWkI7GY2uAKNWg6YqRz5zIMMf/h7YqAtvAD1QNIOLOb7UlE62II=
