os:
- linux
- osx

language:
- node_js

node_js:
- '6.5'

branches:
  only:
  - /^ready\/.*$/

sudo: required

install:
  - echo Install Dependencies
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python-pip python-dev          ; fi
  - sudo pip install dronekit
  - sudo pip install dronekit-sitl

before_script:

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo Start Virtual Screen;
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      echo Package project;
      npm run package:linux; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo Package project;
      npm run package:mac; fi

jobs:
  include:
    - stage: test
      script:
      - npm run test

    - stage: integration
      script:
      - |-
        git clone "https://github.com/"$TRAVIS_REPO_SLUG".git" temp_repo;
        cd temp_repo;

        echo Mergin;
        git merge --ff-only origin/"$TRAVIS_BRANCH";

        echo Pushing;
        git push https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG master;

    - stage: code Coverage

      script:
        - npm run coverage
        - npm run check


    - stage: deliver GitHub Release
      os:
        - osx
        - linux
      before_deploy:
      - |-
        echo "Deploying to GitHub releases ..."
        echo Pull Tags;
        git fetch --tags;

        echo get Latest Tag;
        VERSION=`git describe --tags $(git rev-list --tags --max-count=1)`;
        VERSION_BITS=(${VERSION//./ });
        VNUM1=${VERSION_BITS[0]};
        VNUM2=${VERSION_BITS[1]};
        VNUM3=${VERSION_BITS[2]};
        echo $VERSION;

        echo Tag update;

        VNUM3=$((VNUM3+1));

        NEW_TAG="$VNUM1.$VNUM2.$VNUM3";
        echo "Updating $VERSION to $NEW_TAG";
        git tag $NEW_TAG;
        git push -q https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG --tags;

      script:
      - |-
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        tar cvf rct-groundcontrol-linux-x64.tar out/rct-groundcontrol-linux-x64; fi
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        tar cvf rct-groundcontrol-darwin-x64.tar out/rct-groundcontrol-darwin-x64/rct-groundcontrol.app/Contents/MacOS; fi

      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file:

        - "rct-groundcontrol-linux-x64.tar"
        - "rct-groundcontrol-darwin-x64.tar"

        skip_cleanup: true
        on:
          tags: false
          all_branches: true

    - stage: cleanup
      script: git push https://$GH_TOKEN@github.com/"$TRAVIS_REPO_SLUG" --delete "$TRAVIS_BRANCH";


cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
    on_failure: change
env:
  global:
    secure: rtXOe/h1xXzFgq6MhWVpkNfVwO9TafMZBzq0NExniEcxAQPgxI+R2OkBNd9nndljtTExVKrD2EaVy1PtlV8X984tSVpRKAROXUhAaajnlVmG6jJ2hW9rbqb2Bs4PB4mUeift9B+LACSdAfkBewNGKWcqShXl6qaxNXxkrV8IwwixhS19dA+P4M/Nd62huUw/TCP6px6KTiRk8mPsHrUs2PtPXH8CZJ72tuI233qZgb7JzKmFvcl/6s4+8Z6Jv6/xW5zg0LWo3Nj/UrapcqQfu/+isGumr3GQ82C1CYCceVvjtIbP797tlKWlwOvefoK3bLhF7uvQbTFmbziqJeAl5OgfGqnkNj5YOcEj+7XGZ39XbpdvTGuIbwNP0Hb3Yh8HH6NR7ZEHT05mIg26maiRdwTEXDHkyfADzwgqy40Gyh+mtAH8DJZ2HJXd5mQof4lbljPkzIwkdFZEF3n77ZKOIFPqxTMtQHQurK4ONmZEIJxxlr/xmeG/QWSfsrk2KtegnXCgVURltY6cFST2ZgTURdT6wjX4Rgtt2uTqtHi50YzjR4RT5xlmXy69iFSts/OVcdjZaYQXknr9tUfeNUefyGTpWiujjjynLLBElTYZKAdnmVzw2xBf5yghSWkI7GY2uAKNWg6YqRz5zIMMf/h7YqAtvAD1QNIOLOb7UlE62II=
