os:
- linux
- osx

language:
- node_js

node_js:
- '7.0'

branches:
  only:
  - /^ready\/.*$/

sudo: required

install:
  - echo Install Dependencies
  - yarn install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python-pip python-dev          ; fi
  - sudo pip install dronekit
  - sudo pip install dronekit-sitl

before_script:

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo Start Virtual Screen;
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      echo Package project;
      yarn run package:linux; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo Package project;
      yarn run package:mac; fi

jobs:
  include:
    - stage: test
      script:
      - yarn test

    - stage: integration
      install: skip
      before_script: skip
      script:
      - |-
        git clone "https://github.com/"$TRAVIS_REPO_SLUG".git" temp_repo;
        cd temp_repo;

        echo Mergin;
        git merge --ff-only origin/"$TRAVIS_BRANCH";

        echo Pushing;
        git push https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG master;

    - stage: code Coverage

      script:
        - yarn run coverage
        - yarn run check

    - stage: Functional Test
      os:
      - osx

      script:
        - yarn run functional_test

    - stage: Functional Test
      os:
        - linux

      script:
            - yarn run functional_test

    - stage: tag commit

      install: skip
      before_script: skip
      script:
      - |-
          git fetch --tags;

          echo Latest Tag;
          VERSION=`git describe --tags $(git rev-list --tags --max-count=1)`;
          VERSION_BITS=(${VERSION//./ });
          VNUM1=${VERSION_BITS[0]};
          VNUM2=${VERSION_BITS[1]};
          VNUM3=${VERSION_BITS[2]};
          echo $VERSION;

          VNUM3=$((VNUM3+1));

          NEW_TAG="$VNUM1.$VNUM2.$VNUM3";
          echo "Updating $VERSION to $NEW_TAG";
          git tag $NEW_TAG;
          git push -q https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG --tags;

    - stage: deliver GitHub Release
      os:
        - osx

      script:

        - yarn run package:mac:dmg
        - tar cvf rct-groundcontrol-darwin-x64.tar out/rct-groundcontrol-darwin-x64


      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file:

        - "rct-groundcontrol-darwin-x64.tar"
        - "rct-groundcontrol-darwin.dmg"

        skip_cleanup: true
        on:
          tags: false
          all_branches: true

    - stage: deliver GitHub Release
      os:
        - linux

      script:
      - tar cvf rct-groundcontrol-linux-x64.tar out/rct-groundcontrol-linux-x64

      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file:
        - "rct-groundcontrol-linux-x64.tar"

        skip_cleanup: true
        on:
          tags: false
          all_branches: true

    - stage: cleanup

      install: skip
      before_script: skip

      script: git push https://$GH_TOKEN@github.com/"$TRAVIS_REPO_SLUG" --delete "$TRAVIS_BRANCH";


cache:
  yarn: true


notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    secure: rtXOe/h1xXzFgq6MhWVpkNfVwO9TafMZBzq0NExniEcxAQPgxI+R2OkBNd9nndljtTExVKrD2EaVy1PtlV8X984tSVpRKAROXUhAaajnlVmG6jJ2hW9rbqb2Bs4PB4mUeift9B+LACSdAfkBewNGKWcqShXl6qaxNXxkrV8IwwixhS19dA+P4M/Nd62huUw/TCP6px6KTiRk8mPsHrUs2PtPXH8CZJ72tuI233qZgb7JzKmFvcl/6s4+8Z6Jv6/xW5zg0LWo3Nj/UrapcqQfu/+isGumr3GQ82C1CYCceVvjtIbP797tlKWlwOvefoK3bLhF7uvQbTFmbziqJeAl5OgfGqnkNj5YOcEj+7XGZ39XbpdvTGuIbwNP0Hb3Yh8HH6NR7ZEHT05mIg26maiRdwTEXDHkyfADzwgqy40Gyh+mtAH8DJZ2HJXd5mQof4lbljPkzIwkdFZEF3n77ZKOIFPqxTMtQHQurK4ONmZEIJxxlr/xmeG/QWSfsrk2KtegnXCgVURltY6cFST2ZgTURdT6wjX4Rgtt2uTqtHi50YzjR4RT5xlmXy69iFSts/OVcdjZaYQXknr9tUfeNUefyGTpWiujjjynLLBElTYZKAdnmVzw2xBf5yghSWkI7GY2uAKNWg6YqRz5zIMMf/h7YqAtvAD1QNIOLOb7UlE62II=

